### PR TITLE
Formatted and added namespace in URDF launch file

### PR DESCRIPTION
**Pull request by hardesh-peppermint**
Hi,

I've added a launch argument of namespace in the urdf launch file. Hoping that this will help others as well.

### CODE REVIEW

**Comment by hardesh-peppermint** [comment]
Hi @saching13,
Just following up on this PR. Let me know if you need anything from my end

**Comment by saching13** [comment]
Sorry for the delay. 
Since there are lot of alignment changes I couldn't review it quickly. 
If you can revert the rest and keep the main changes I could review it faster. If thats okay.
If not. I will go over it sometime next week.

**Comment by hardesh-peppermint** [comment]
Sure. I'll revert the formatting changes. 
btw are there any plans to use `black` (https://github.com/psf/black) to format the code in this repo?

**Comment by saching13** [comment]
@hardesh-peppermint  no plans for black. Plan is there to look for one. mostly will use pep8 or ros2 default standard.

**Pull request merged**
