### PR TITLE
OAK-1-MAX non stereo / non spatial YOLO example node

### PR DESCRIPTION
**Pull request by MAVProxyUser**
Tested successfully with OAK-1-MAX, OAK-D-S2, OAK-D-PRO. 
[Original OpenCV AI Kit: Oak-1](https://store.opencv.ai/products/oak-1) version failed with following error:
```
[yolov4_image_node-1]   what():  There is no Camera data available corresponding to the the requested cameraId
```
This is likely due to "Device type:" being reported as blank
https://github.com/luxonis/depthai-ros/issues/257#issuecomment-1480627256
```
[component_container-1] [INFO] [1679549436.807773594] [oak]: Device type: 
```

To test with other cams launch with:
```
ros2 launch depthai_examples yolov4_publisher_nodepth.launch.py camera_model:=OAK-1-MAX
```

Query YOLO hits with:
```
ubuntu@ubuntu:/tmp/depthai-ros$ ros2 topic list 
/color/camera_info
/color/image
/color/yolov4_Img_detections
/joint_states
/parameter_events
/robot_description
/rosout
/tf
/tf_static
ubuntu@ubuntu:/tmp/depthai-ros$ ros2 topic hz /color/yolov4_Img_detections
average rate: 19.158
	min: 0.002s max: 0.109s std dev: 0.04062s window: 21
average rate: 19.203
	min: 0.002s max: 0.109s std dev: 0.04038s window: 42
average rate: 19.233
	min: 0.002s max: 0.109s std dev: 0.03964s window: 62
average rate: 19.447
	min: 0.002s max: 0.109s std dev: 0.03927s window: 83
ubuntu@ubuntu:/tmp/depthai-ros$ ros2 topic echo /color/yolov4_Img_detections
---
header:
  stamp:
    sec: 1679631788
    nanosec: 407148768
  frame_id: oak_rgb_camera_optical_frame
detections: []
---
header:
  stamp:
    sec: 1679631788
    nanosec: 457638565
  frame_id: oak_rgb_camera_optical_frame
detections:
- header:
    stamp:
      sec: 0
      nanosec: 0
    frame_id: ''
  results:
  - hypothesis:
      class_id: '63'
      score: 0.5892834663391113
    pose:
      pose:
        position:
          x: 0.0
          y: 0.0
          z: 0.0
        orientation:
          x: 0.0
          y: 0.0
          z: 0.0
          w: 1.0
      covariance:
      - 0.0
      - 0.0
      - 0.0
      - 0.0
...
  bbox:
    center:
      position:
        x: 73.0
        y: 306.0
      theta: 0.0
    size_x: 148.0
    size_y: 238.0
  id: '63'
---

```

### CODE REVIEW

**Comment by Serafadam** [comment]
Hi, thanks a lot!, minor comment, I'd change it to use the same launch file as current yolo launch, and just add argument to choose if we want spatial version or not.

**Comment by MAVProxyUser** [comment]
Cool @Serafadam it was a stretch for me to get this sorted out. I may need to rely on you for that last mile. I'm not super familiar with launch file semantics.

**Comment by MAVProxyUser** [comment]
@Serafadam in your opinion what would be the best way to handle the small differences? If camera_model is OAK-1 then launch the other node? That seem reasonable?  

```
ubuntu@ubuntu:~/depthai-ros$  diff depthai_examples/launch/yolov4_publisher_nodepth.launch.py depthai_examples/launch/yolov4_publisher.launch.py 
22c22
<     camera_model = LaunchConfiguration('camera_model',  default = 'OAK-1-MAX')
---
>     camera_model = LaunchConfiguration('camera_model',  default = 'OAK-D')
35a36
>     subpixel           = LaunchConfiguration('subpixel',          default = True)
38a40,41
>     lrCheckTresh       = LaunchConfiguration('lrCheckTresh',      default = 5)
>     monoResolution     = LaunchConfiguration('monoResolution',  default = '400p')
43c46
<         description='The model of the camera. Using a wrong camera model can disable camera features. Valid models: `OAK-1, OAK-1-MAX`.')
---
>         description='The model of the camera. Using a wrong camera model can disable camera features. Valid models: `OAK-D, OAK-D-LITE`.')
99a103,107
>     declare_subpixel_cmd = DeclareLaunchArgument(
>         'subpixel',
>         default_value=subpixel,
>         description='Enables subpixel stereo detection.')
> 
114a123,132
>     declare_lrCheckTresh_cmd = DeclareLaunchArgument(
>         'lrCheckTresh',
>         default_value=lrCheckTresh,
>         description='LR Threshold is the threshod of how much off the disparity on the l->r and r->l  ')
> 
>     declare_monoResolution_cmd = DeclareLaunchArgument(
>         'monoResolution',
>         default_value=monoResolution,
>         description='Contains the resolution of the Mono Cameras. Available resolutions are 800p, 720p & 400p for OAK-D & 480p for OAK-D-Lite.')
>   
129,130c147,148
<     yolov4_image_node = launch_ros.actions.Node(
<             package='depthai_examples', executable='yolov4_image_node',
---
>     yolov4_spatial_node = launch_ros.actions.Node(
>             package='depthai_examples', executable='yolov4_spatial_node',
136c154,155
<                         {'resourceBaseFolder': resourceBaseFolder}])
---
>                         {'resourceBaseFolder': resourceBaseFolder},
>                         {'monoResolution': monoResolution}])
157a177
>     ld.add_action(declare_subpixel_cmd)
160a181,182
>     ld.add_action(declare_lrCheckTresh_cmd)
>     ld.add_action(declare_monoResolution_cmd)
162c184
<     ld.add_action(yolov4_image_node)
---
>     ld.add_action(yolov4_spatial_node)
```

**Comment by Serafadam** [comment]
Instead of device check, I'd add a `spatial` flag that launches given node, in cpp we can probe device how much sensors it has and return error if it only has one sensor (that's basically how it works now in [depthai_ros_driver](https://github.com/luxonis/depthai-ros/blob/5221d3039ff9bc6e0af2da0c1367c35caf96fe72/depthai_ros_driver/src/pipeline_generator.cpp#L28))

**Comment by MAVProxyUser** [comment]
Ok I got some logic in the launch file, I've got to get all this mess split out now. 

```
$ diff depthai_examples/src/yolov4_image_publisher.cpp depthai_examples/src/yolov4_spatial_publisher.cpp
8c8,9
< #include "depthai_bridge/ImgDetectionConverter.hpp"
---
> #include "depthai_bridge/SpatialDetectionConverter.hpp"
> #include "depthai_ros_msgs/msg/spatial_detection_array.hpp"
18c19,21
< #include "depthai/pipeline/node/DetectionNetwork.hpp"
---
> #include "depthai/pipeline/node/MonoCamera.hpp"
> #include "depthai/pipeline/node/SpatialDetectionNetwork.hpp"
> #include "depthai/pipeline/node/StereoDepth.hpp"
32,33c35
< dai::Pipeline createPipeline(bool syncNN, std::string nnPath, int confidence) {
<     // Create pipeline
---
> dai::Pipeline createPipeline(bool syncNN, bool subpixel, std::string nnPath, int confidence, int LRchecktresh, std::string resolution) {
34a37,42
>     dai::node::MonoCamera::Properties::SensorResolution monoResolution;
>     auto colorCam = pipeline.create<dai::node::ColorCamera>();
>     auto spatialDetectionNetwork = pipeline.create<dai::node::YoloSpatialDetectionNetwork>();
>     auto monoLeft = pipeline.create<dai::node::MonoCamera>();
>     auto monoRight = pipeline.create<dai::node::MonoCamera>();
>     auto stereo = pipeline.create<dai::node::StereoDepth>();
36,38c44
<     // Define sources and outputs
<     auto camRgb = pipeline.create<dai::node::ColorCamera>();
<     auto detectionNetwork = pipeline.create<dai::node::YoloDetectionNetwork>();
---
>     // create xlink connections
40c46,47
<     auto nnOut = pipeline.create<dai::node::XLinkOut>();
---
>     auto xoutDepth = pipeline.create<dai::node::XLinkOut>();
>     auto xoutNN = pipeline.create<dai::node::XLinkOut>();
42,43c49,69
<     xoutRgb->setStreamName("rgb");
<     nnOut->setStreamName("detections");
---
>     xoutRgb->setStreamName("preview");
>     xoutNN->setStreamName("detections");
>     xoutDepth->setStreamName("depth");
> 
>     colorCam->setPreviewSize(416, 416);
>     colorCam->setResolution(dai::ColorCameraProperties::SensorResolution::THE_1080_P);
>     colorCam->setInterleaved(false);
>     colorCam->setColorOrder(dai::ColorCameraProperties::ColorOrder::BGR);
> 
>     if(resolution == "720p") {
>         monoResolution = dai::node::MonoCamera::Properties::SensorResolution::THE_720_P;
>     } else if(resolution == "400p") {
>         monoResolution = dai::node::MonoCamera::Properties::SensorResolution::THE_400_P;
>     } else if(resolution == "800p") {
>         monoResolution = dai::node::MonoCamera::Properties::SensorResolution::THE_800_P;
>     } else if(resolution == "480p") {
>         monoResolution = dai::node::MonoCamera::Properties::SensorResolution::THE_480_P;
>     } else {
>         RCLCPP_ERROR(rclcpp::get_logger("rclcpp"), "Invalid parameter. -> monoResolution: %s", resolution.c_str());
>         throw std::runtime_error("Invalid mono camera resolution.");
>     }
45,61c71,99
<     // Properties
<     camRgb->setPreviewSize(416, 416);
<     camRgb->setResolution(dai::ColorCameraProperties::SensorResolution::THE_1080_P);
<     camRgb->setInterleaved(false);
<     camRgb->setColorOrder(dai::ColorCameraProperties::ColorOrder::BGR);
<     camRgb->setFps(40);
< 
<     // Network specific settings
<     detectionNetwork->setConfidenceThreshold(0.5f);
<     detectionNetwork->setNumClasses(80);
<     detectionNetwork->setCoordinateSize(4);
<     detectionNetwork->setAnchors({10, 14, 23, 27, 37, 58, 81, 82, 135, 169, 344, 319});
<     detectionNetwork->setAnchorMasks({{"side26", {1, 2, 3}}, {"side13", {3, 4, 5}}});
<     detectionNetwork->setIouThreshold(0.5f);
<     detectionNetwork->setBlobPath(nnPath);
<     detectionNetwork->setNumInferenceThreads(2);
<     detectionNetwork->input.setBlocking(false);
---
>     monoLeft->setResolution(monoResolution);
>     monoLeft->setBoardSocket(dai::CameraBoardSocket::LEFT);
>     monoRight->setResolution(monoResolution);
>     monoRight->setBoardSocket(dai::CameraBoardSocket::RIGHT);
> 
>     /// setting node configs
>     stereo->initialConfig.setConfidenceThreshold(confidence);
>     stereo->setRectifyEdgeFillColor(0);  // black, to better see the cutout
>     stereo->initialConfig.setLeftRightCheckThreshold(LRchecktresh);
>     stereo->setSubpixel(subpixel);
>     stereo->setDepthAlign(dai::CameraBoardSocket::RGB);
> 
>     spatialDetectionNetwork->setBlobPath(nnPath);
>     spatialDetectionNetwork->setConfidenceThreshold(0.5f);
>     spatialDetectionNetwork->input.setBlocking(false);
>     spatialDetectionNetwork->setBoundingBoxScaleFactor(0.5);
>     spatialDetectionNetwork->setDepthLowerThreshold(100);
>     spatialDetectionNetwork->setDepthUpperThreshold(5000);
> 
>     // yolo specific parameters
>     spatialDetectionNetwork->setNumClasses(80);
>     spatialDetectionNetwork->setCoordinateSize(4);
>     spatialDetectionNetwork->setAnchors({10, 14, 23, 27, 37, 58, 81, 82, 135, 169, 344, 319});
>     spatialDetectionNetwork->setAnchorMasks({{"side13", {3, 4, 5}}, {"side26", {1, 2, 3}}});
>     spatialDetectionNetwork->setIouThreshold(0.5f);
> 
>     // Link plugins CAM -> STEREO -> XLINK
>     monoLeft->out.link(stereo->left);
>     monoRight->out.link(stereo->right);
63,64c101,102
<     // Linking
<     camRgb->preview.link(detectionNetwork->input);
---
>     // Link plugins CAM -> NN -> XLINK
>     colorCam->preview.link(spatialDetectionNetwork->input);
66c104
<         detectionNetwork->passthrough.link(xoutRgb->input);
---
>         spatialDetectionNetwork->passthrough.link(xoutRgb->input);
68c106
<         camRgb->preview.link(xoutRgb->input);
---
>         colorCam->preview.link(xoutRgb->input);
70c108
<     detectionNetwork->out.link(nnOut->input);
---
>     spatialDetectionNetwork->out.link(xoutNN->input);
71a110,111
>     stereo->depth.link(spatialDetectionNetwork->inputDepth);
>     spatialDetectionNetwork->passthroughDepth.link(xoutDepth->input);
77c117
<     auto node = rclcpp::Node::make_shared("yolov4_img_node");
---
>     auto node = rclcpp::Node::make_shared("yolov4_spatial_node");
82,83c122,124
<     bool syncNN;
<     int confidence = 200;
---
>     bool syncNN, subpixel;
>     int confidence = 200, LRchecktresh = 5;
>     std::string monoResolution = "400p";
87a129
>     node->declare_parameter("subpixel", true);
89a132,133
>     node->declare_parameter("LRchecktresh", LRchecktresh);
>     node->declare_parameter("monoResolution", monoResolution);
94a139
>     node->get_parameter("subpixel", subpixel);
95a141,142
>     node->get_parameter("LRchecktresh", LRchecktresh);
>     node->get_parameter("monoResolution", monoResolution);
109,111c156
<     dai::Pipeline pipeline = createPipeline(syncNN, nnPath, confidence);
< 
<     // Connect to device and start pipeline
---
>     dai::Pipeline pipeline = createPipeline(syncNN, subpixel, nnPath, confidence, LRchecktresh, monoResolution);
113a159,161
>     auto colorQueue = device.getOutputQueue("preview", 30, false);
>     auto detectionQueue = device.getOutputQueue("detections", 30, false);
>     auto depthQueue = device.getOutputQueue("depth", 30, false);
116,118c164,180
<     // Output queues will be used to get the rgb frames and nn data from the outputs defined above
<     auto qRgb = device.getOutputQueue("rgb", 4, false);
<     auto qDet = device.getOutputQueue("detections", 4, false);
---
>     int width, height;
>     if(monoResolution == "720p") {
>         width = 1280;
>         height = 720;
>     } else if(monoResolution == "400p") {
>         width = 640;
>         height = 400;
>     } else if(monoResolution == "800p") {
>         width = 1280;
>         height = 800;
>     } else if(monoResolution == "480p") {
>         width = 640;
>         height = 480;
>     } else {
>         RCLCPP_ERROR(rclcpp::get_logger("rclcpp"), "Invalid parameter. -> monoResolution: %s", monoResolution.c_str());
>         throw std::runtime_error("Invalid mono camera resolution.");
>     }
120a183,186
>     if(height > 480 && boardName == "OAK-D-LITE") {
>         width = 640;
>         height = 480;
>     }
124c190
<     dai::rosBridge::BridgePublisher<sensor_msgs::msg::Image, dai::ImgFrame> rgbPublish(qRgb,
---
>     dai::rosBridge::BridgePublisher<sensor_msgs::msg::Image, dai::ImgFrame> rgbPublish(colorQueue,
136,139c202,204
<     dai::rosBridge::ImgDetectionConverter detConverter(tfPrefix + "_rgb_camera_optical_frame", 416, 416, false);
< 
<     dai::rosBridge::BridgePublisher<vision_msgs::msg::Detection2DArray, dai::ImgDetections> detectionPublish(
<         qDet,
---
>     dai::rosBridge::SpatialDetectionConverter detConverter(tfPrefix + "_rgb_camera_optical_frame", 416, 416, false);
>     dai::rosBridge::BridgePublisher<depthai_ros_msgs::msg::SpatialDetectionArray, dai::SpatialImgDetections> detectionPublish(
>         detectionQueue,
141,142c206,207
<         std::string("color/yolov4_Img_detections"),
<         std::bind(&dai::rosBridge::ImgDetectionConverter::toRosMsg, &detConverter, std::placeholders::_1, std::placeholders::_2),
---
>         std::string("color/yolov4_Spatial_detections"),
>         std::bind(&dai::rosBridge::SpatialDetectionConverter::toRosMsg, &detConverter, std::placeholders::_1, std::placeholders::_2),
143a209,221
> 
>     dai::rosBridge::ImageConverter depthConverter(tfPrefix + "_right_camera_optical_frame", true);
>     auto rightCameraInfo = depthConverter.calibrationToCameraInfo(calibrationHandler, dai::CameraBoardSocket::RIGHT, width, height);
>     dai::rosBridge::BridgePublisher<sensor_msgs::msg::Image, dai::ImgFrame> depthPublish(
>         depthQueue,
>         node,
>         std::string("stereo/depth"),
>         std::bind(&dai::rosBridge::ImageConverter::toRosMsg, &depthConverter, std::placeholders::_1, std::placeholders::_2),
>         30,
>         rightCameraInfo,
>         "stereo");
> 
>     depthPublish.addPublisherCallback();
```

**Comment by MAVProxyUser** [comment]
Ok @Serafadam I did my best! Sadly I had to move off my humble install for compatibility with other devices. I'm on noetic for the time being. Perhaps you can see if I got it right!?

**Comment by Serafadam** [comment]
LGTM, could you change target branche to `humble`?

**Comment by MAVProxyUser** [comment]
> LGTM, could you change target branche to `humble`?

I think I tried to... but now it says "This branch has conflicts that must be resolved". Do you know how to handle that?

**Comment by MAVProxyUser** [comment]
@Serafadam do you need me to rebase, or do something else with this?

**Comment by Serafadam** [comment]
Hi @MAVProxyUser, sorry for the delay, it seems that you either need to pull changes from `humble` branch and resolve confilcts. You could also try creating a new branch from humble and apply those changes here, that's probably a simpler way. I can also do that after my current backlog clears up a little bit.

**Comment by MAVProxyUser** [comment]
This look any better @Serafadam ?

**Pull request merged**
