### PR TITLE
Add generic pipeline publisher 

### PR DESCRIPTION
**Pull request by jdavidberger**
The main feature added here is a publisher added that reads through the pipeline and exposes sort of what one might expect in terms of endpoints. 

An auxillary / somewhat tangental feature also is the integration of a dynamic reconfigure server to allow for runtime adjustment of parameters. Right now it's just for stereo depth. I didn't want to go all out and add more until the feature direction itself was validated since this PR had already gotten away from me a little bit.

See https://github.com/jdavidberger/depthai-ros-examples/commit/42b6738c61e6d69ddcf809b887a5a568e3ae29c8 for use of the new publisher.

### CODE REVIEW

**Comment by jdavidberger** [comment]
Is this still up for review? Haven't heard anything on it in a while

**Comment by saching13** [comment]
> Is this still up for review? Haven't heard anything on it in a while

I think we discussed on slack that it doesn't really add much additional value by adding another generic publisher.

**Comment by jdavidberger** [comment]
I was sorta under the impression it was going to get rolled in as support for a monolithic node from how the conversation ended there. The reason I ask is that the dynamic reconfigure stuff is important for one of our projects and if it's not in mainline I'll have to just commit to adding all of it to our internal tooling.

**Comment by saching13** [comment]
I'm up for the dynamic reconfigure part. Can't we add that as a converter to existing model and create a monolithic node/nodelet using the same ? 
Note that we want to do that such a way we support both ros1 and ros2.

**Comment by jdavidberger** [comment]
The dynamic reconfigure portion is mostly orthogonal and could be separated out. But to be honest, it's intractable to re-describe our pipelines all over again for the benefit of a creating a rosnode so it's sort of a moot point for me.

**Pull request closed without merging**
